### ISSUE TITLE
Insight on `adend`, `adended`, and `ended`.

### ISSUE THREAD

**Issue by chemoish** [videojs/videojs-contrib-ads#108]
Can anyone provide insight to the following events—How they get called and when?

- `adend`
- `adended`
- `ended`

*Where does the 'ed come from?*

It looks like `adended` gets fired when an any `src` finishes during `startLinearAdMode()`.

It looks like `adend` gets fired when you fire `endLinearAdMode()`. This seems to only change the state to `content-resuming`.

I am not sure when `ended` gets fired, but it seems like all plugin events are registered upon instantiation (and are not dynamic)…

```js
player.on('ended', function () { console.warn('ended 1'); }); // fires on ad end

player.ads();

player.on('ended', function () { console.warn('ended 2'); }); // does not fire on ad end
```

---

This begs the question…

How does this integrate with `endcard`'s?

```js
player.on('ended', function () {
    // showEndcard();
});
```

---

Anyways, atm I am just:

1. Register ads for preroll—hope no one sets `ended` event before me
1. Register endcard—sets `ended` event
1. Register src—utilizes `ended` event

The only thing I don't like is the dependency order requirement that get created due to these events.

**Comment by gkatsev** [comment]
Basically, the idea of the 2.0 release is to hide any of the ad workings from any plugins listening down stream. So, a plugin could just listen to `playing` and `ended` and know when a video starts and ends and not need to worry about whether ads are playing currently or not. To do so, events are prefixed -- and redispatched in case a downstream user *does* want to know about ads -- to hide them by default.
Around each ad block, we fire `adstart` and `adend` events for users to know when we enter ad playback and when we leave ad playback. These are our own events that are fired.
Regular video lifecycle events during an ad will get prefixed with `ad`, so, the usual `play`, `playing`, `pause`, `ended` would turn into `adplay`, `adplaying`, `adpause`, `adended`. 
Some of the events during a video also need to be prefixed, for example, the `ended` event, since there might be a postroll. Those events get prefixed with `content`, so, `ended` becomes `contentended`. `ended` gets special attention because we make sure that `ended` gets fired after all the postrolls are done to make sure that downstream users know the video and all ads are done.
So, a typical video's events could look something like:
1. `loadstart`
1. `loadedmetadata`
1. `canplay`
1. `canplaythrough`
1. `play`
1. `playing`
1. `pause`
1. `play`
1. `ended`
This will apply to a regular video or a video that has ads. Assuming a single pre-roll and a single post-roll, the full event log could look something like:
1. `loadstart`
1. `loadedmetadata`
1. `canplay`
1. `canplaythrough`
1. `play`
1. `playing`
1. `adstart`
1. `adplay`
1. `adplaying`
1. `adended`
1. `adend`
1. `pause`
1. `play`
1. `contentended`
1. `adstart`
1. `adplay`
1. `adplaying`
1. `adended`
1. `adend`
1. `ended`

While we didn't like the dependency order requirement for this plugin we felt like this was the best possibly solution that would keep all the ads details contained to this plugin. Hope the above gives some more insight into our thought process and what actually happens.

**Comment by chemoish** [comment]
The example debug made it pretty clear, but just wanted to verify.

Thanks.

![screen shot 2015-08-18 at 11 14 51 am](https://cloud.githubusercontent.com/assets/549319/9338623/7ffe3986-459a-11e5-8100-788d91b5b62b.png)
