### ISSUE TITLE
original 'play' event needed by video.js, suppressed by contrib-ads

### ISSUE THREAD

**Issue by hc2p** [videojs/videojs-contrib-ads#140]
Hi,
when resuming after a preroll ended (the ads.state is `content-resuming`), the `play` event is suppressed (propagation stopped) by the ads-plugin. This will leave several callbacks within videojs un-called, e.g. `playToggle.handlePlay`.

What's the idea behind suppressing the original event? Isn't the prefixing only for additional handlers so you can have specific ad-only, content-only callbacks? 

Thanks for looking into this.

**Comment by vadikace** [comment]
Also have an issue with this when ads state going in this flow ad-playback -> content-resuming. And how to go from content-resuming state because it's suppresses timeupdate and play events.

**Comment by vadikace** [comment]
@gkatsev can you give some feedback please. Because it's open since 8 Jan.

**Comment by incompl** [comment]
When an ad resumes there is a `playing` event (since content started playing) but no `play` event (since there was no specific directive to play, like clicking the play button), and generally people use the `playing` event to catch this situation. Are there any current bugs that result from this way of things?
