### ISSUE TITLE
Add support for preroll before live video

### ISSUE THREAD

**Issue by nonth** [videojs/videojs-contrib-ads#166]
Hi, I am trying to use the ads plugin to play preroll ads on HLS live stream (ads video is in mp4 format)

When playing live stream player.duration return infinity and contrib-ads will get snapshot when browser is iOS or player.duration is not infinity

A code below is from fsmHandler function in 'ad-playback' state

``` javascript

// capture current player state snapshot (playing, currentTime, src)
if (videojs.browser.IS_IOS || player.duration() !== Infinity) {
    this.snapshot = getPlayerSnapshot(player);
}

```

Why we have to check player.duration() is not infinity before get a snapshot ? and is it possible to fix this issue by remove check player.duration() !== Infinity ?
## Versions
- videojs - v5.9.2
- videojs-contrib-hls - v1.3.11
- videojs-contrib-ads - v3.2.0

**Comment by incompl** [comment]
The reason the code doesn't take snapshots for live streams is because ads _during_ a live stream typically do not pause the content video, they are played over it. In your case, I assume you are trying to play a preroll before the live stream itself starts, which is why you want a snapshot, yes? Maybe we could add an option for something like `useSnapshotWhenLive`. What do you think?

**Comment by apesant** [comment]
Hi, 
I just opened a somewhat similar issue #173
