### ISSUE TITLE
Player spins forever when resuming live m3u8 content after prerolls in Chrome for Android

### ISSUE THREAD

**Issue by apesant** [videojs/videojs-contrib-ads#199]
So I think I've found an issue in contrib-ads when the live content is resumed after prerolls (probably after any ad break actually, but haven't tried that).

So what happens is:
- The ads are played 
- we call endLinearAdMode
- the player restores the snapshot
- tryToResume is called
- tryToResume calls resume()
- resume() calls player.currentTime(0), which breaks playback (spinner appears and stays forever)

The way I fixed it in my integration was to change this line in the `resume` method:
`if (videojs.browser.IS_IOS  && player.ads.isLive(player)) {`

to this line 

`if ((videojs.browser.IS_IOS || (videojs.browser.IS_ANDROID && videojs.browser.IS_CHROME)) && player.ads.isLive(player)) {`

This way player.currentTime(0) is not called. 

Can you guys look into this ? I'm not sure my local fix is the real issue there, or if the bug is in `currentTime()`

Thanks!

cc @JulienCr

**Comment by incompl** [comment]
The reason this code doesn't do what you expect is because our support for live video assumes ads are played based on cues in the live stream such as ID3 tags. Support for prerolls or postrolls in live video is not officially supported. One big difference in this mode is that the live stream plays muted in the background during the ad where possible (assuming that there is an interstitial or break in the live stream when the ad is prompted).

We could add support for prerolls before live streams and I think that'd be a useful feature for sure. In order to do that fully and without breaking the current live support, we'd probably need to make additional changes from what you suggest.

Given the quantity and nuance of the use cases supported by this plugin, I would want to make the code explicit about the scenarios that are passing through these methods. For example, we might introduce a new option and write code like this:

```js
if (player.ads.isLive(player) && player.ads.livePreroll) {
  // New code
} else {
  // Existing code
}
```

We've had some discussions about doing something like this and while we aren't working on it yet, we would love feedback.

**Comment by mrinvidi** [comment]
@incompl - Was this ever implemented?

**Comment by incompl** [comment]
@mrinvidi Yes it was! Check out (the new liveCuePoints option)[http://videojs.github.io/videojs-contrib-ads/integrator/options.html]
