### ISSUE TITLE
Problem taking snapshot whith source in HLS/DASH

### ISSUE THREAD

**Issue by mimcz** [videojs/videojs-contrib-ads#255]
I have an issue when I´m trying to setup ads plugin with content video in MSE formate (HLS/DASH). The snapshot source is taken as `blob: URI` instead of manifest source. So when trying to restore the snapshot after preroll it fails on this. Anyone had same problem?

**Comment by alex-barstow** [comment]
The snapshot should also restore `player.currentSrc()` which contains the manifest source. Do you have more specifics about what exactly is happening, or a test page where the problem occurs?

**Comment by forbesjo** [comment]
I think the snapshot (https://github.com/videojs/videojs-contrib-ads/blob/master/src/snapshot.js#L37) should instead use `player.currentSource()`

**Comment by alex-barstow** [comment]
using `currentSource()` would also simplify the restoration of `withCredentials` or any DRM key systems

**Comment by mimcz** [comment]
In my fork I solved it by not using `player.currentSrc()` to get the content source for snapshot. Instead I get source from `player.ads.contentSrc` and `player.ads.contentType` . This solved all of my issues with it.

**Comment by AdamTyler** [comment]
This still seems to be an issue. Trying to restore a snapshot from `blob:URI` creates an error when the the ad break ends and it tries to restore. The player errors with `MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.`
