### ISSUE TITLE
getPlayerSnapshot multiple calls

### ISSUE THREAD

**Issue by viasors** [videojs/videojs-contrib-ads#256]
Hi, I have problem on Firefox browser with slow internet connection. getPlayerSnapshot method is called twice sometimes. The second method call occurs when the snapshot is already taken and the snapshot is saved from the ad. Do you see the problem of doing a PR where the getPlayerSnapshot method will be called if only null and the restorePlayerSnapshot method would set the snapshot at the end to null?

**Comment by incompl** [comment]
Unfortunately setting the snapshot to null at the end would break some things: there is other code that checks the snapshot for information after the snapshot is restored. We're in the process of removing these types of usages so that we can do exactly what you're suggesting. For example, the refactored `redispatch` in #251 no longer checks the snapshot object. In the meantime, I'm not sure of a workaround; I'm curious to know why getPlayerSnapshot gets called twice. Maybe the issue could be resolved earlier in the process.

**Comment by viasors** [comment]
You're right. But this should be safe, right? [https://github.com/viasors/videojs-contrib-ads/commit/00241ce041d00f881a9dbef789da68a27f00bc99](url)

I think this happens when the pre-roll timeout expires and "pre-roll" starts playing after a few seconds of the video (FF 53).

**Comment by incompl** [comment]
It's hard to say what the consequences will be. We did [something like this](https://github.com/videojs/videojs-contrib-ads/commit/605d5af2ad413c23987f70e32187d8e850134310) recently and found bugs it introduced a couple weeks later and had to roll it back.

Your proposed solution might work for you. I'd recommend testing it very thoroughly. For the safety of the project though, I don't want to merge any changes like this until more refactoring is done.
