### ISSUE TITLE
Playback error when playing one video with ads after another 

### ISSUE THREAD

**Issue by ypavlotsky** [videojs/videojs-contrib-ads#324]
Hi,

I modified the [playlist sample](http://googleads.github.io/videojs-ima/examples/playlist/) for the video.js IMA plugin to play a second video once the first finishes and I'm seeing some weird behavior where once the first video's post-roll finishes, I see the pre-roll for the second video, but then I don't see the video for the second video, just audio, the poster and a loading spinner. The video plays normally if we try to play it afterwards. So we're not sure if this is a contrib-ads issue or a player issue, but figured to check with you first to see if there's something we should be doing differently.

Thanks,
Yury

**Comment by incompl** [comment]
@alex-barstow This sounds like one of the issues you were working on, is it?

**Comment by alex-barstow** [comment]
The symptoms certainly sound similar. The audio-only issue I was working on is unique to a different integration, though I suppose it's possible the underlying cause in contrib-ads is the same.

@ypavlotsky I am not able to reproduce the problem with your linked test page. Is that the modified or unmodified playlist sample? The second video does not autoplay after the postroll of the first video. If I can reproduce the issue I can try to determine whether it's caused by the same bug I'm working on.

**Comment by ypavlotsky** [comment]
The above page was the unmodified sample. I put up the modified code [here](https://ypavlotsky.github.io/vjsima/examples/playlist/).

To repro: click the play button, sit through the preroll on the first video and skip to the end. Sit through the post-roll and then the preroll for the second video, and you'll see the spinner and no content video after that.

Note: it didn't happen 100% of the time for me, so it might be a race condition.

**Comment by alex-barstow** [comment]
So far I've had no luck reproducing this. @ypavlotsky On which platforms have you observed it?

**Comment by ypavlotsky** [comment]
Just went back to try to repro it and now I can't get it to happen either. I'll close this out and comment back here if I run into it again. FWIW, I'm running Chrome 64 on Linux.
