### ISSUE TITLE
Add an option to force contrib-ads to treat content as live 

### ISSUE THREAD

**Issue by sunilkumarjena21** [videojs/videojs-contrib-ads#344]
Hi @incompl ,

We are implementing Google IMA ads at 'cuechange' metadata event listener. After Lot of try we are unable to get shouldPlayContentBehindAd integrate properly with our implementation.Please note this implementation is for live stream.We want suggestion from your side,what should be the best approach to implement this.Some code snippet with the correct position to call will do our job little easier.

Any help will be highly appreciated!

Attached code for your kind perusal.

Thanks
Sunil

**Comment by incompl** [comment]
I wonder if this is related to #305 and #306. Are you finding that your player doesn't report the duration as `Infinity`? Maybe we do need something like #306 if so.

**Comment by sunilkumarjena21** [comment]
hi @incompl ,

Thanks for your swift response. I think this will actually be difficult with the IMA plugin - it handles  [contentPauseRequested ](https://github.com/googleads/videojs-ima/blob/master/src/sdk-impl.js#L386)and [contentResumeRequested ](https://github.com/googleads/videojs-ima/blob/master/src/sdk-impl.js#L397) itself.So we are dealing with live stream and using HLS streaming medium.we need to just mute and unmute the sound of video instead of pausing and resuming it.

Could you please let us know how to call `shouldPlayContentBehindAd ` in our case.

Updated code attached for your reference.

**Comment by incompl** [comment]
`shouldPlayContentBehindAd` isn't something you call in order to change the behavior: it returns true/false depending on if contrib-ads detected that behavior. contrib-ads automatically detects if it should do this using this logic:

```js
return !videojs.browser.IS_IOS &&
             !videojs.browser.IS_ANDROID &&
             somePlayer.duration() === Infinity;
```

If you're seeing the live stream pause instead of mute, it probably means that the `player.duration()` is not `Infinity`, as was seen in #305. It sounds like #306 is probably what you're looking for: a way to override the behavior and force it to treat the source as live. Does that make sense?

**Comment by sunilkumarjena21** [comment]
Yes..its making sense.

Thanks

**Comment by incompl** [comment]
PR: https://github.com/videojs/videojs-contrib-ads/pull/374

**Comment by incompl** [comment]
`contentIsLive` option added in 6.3.0, documented here: http://videojs.github.io/videojs-contrib-ads/integrator/options.html
