### ISSUE TITLE
postroll issues

### ISSUE THREAD

**Issue by Pong420** [videojs/videojs-contrib-ads#352]
### Description

I am using `videojs-ima` to handle postroll and receive below warning
```
VIDEOJS: WARN: Unexpected adsready event
```
Is `onAdsReady` function missing in `Postroll` or we should not fire `adsready` event on postroll

[Demo](https://videojs-ads.herokuapp.com/)

---

Another question, fire `nopostroll` event when `contentend` will not receive `eneded` event immediately
```js
player.on("contentended", function(){
   player.trigger("nopostroll")
})
```

### Versions

**videojs-contrib-ads version**: 6.0.0

**Video-js version**: 6.7.4

**Other plugins**: videojs-ima

**Comment by incompl** [comment]
The adsready event is just for preroll handling. I suggest opening an issue with videojs-ima.

When you say ended event is not immediate after calling nopostroll, do you mean that it is delayed or that it never happens? Which version of videojs-contrib-ads are you using?

**Comment by Pong420** [comment]
```js
player.on("contentended", function(){
   player.trigger("nopostroll")
   // ended event is not received at this moment, until content playback ended again 
})
```

**Comment by incompl** [comment]
For the nopostroll issue, here is the issue in videojs-ima to track that enhancement on their side: https://github.com/googleads/videojs-ima/issues/567

I don't see an issue there about adsready / postrolls, so I still suggest opening one. I'm closing this issue because there aren't any changes needed on the contrib-ads side.
