### ISSUE TITLE
Chrome 66 Preroll (user interaction required) onAdsError causing virtual hang

### ISSUE THREAD

**Issue by bill5roses** [videojs/videojs-contrib-ads#392]
### Description

If using Google ima3 and Chrome 66, when video playback requires user interaction, an adserror is fired, but the videojs player stays in a playing mode - showing pause button instead of play button. Also, the play promise catch doesn't seem to be passed through to original player that asked for the play() call.
video.js version 6.10.1
video-contrib-ads version 6.3.0
videojs-ima version 1.3.0

### Steps to Reproduce

Here is a simple demonstration of the issue:
http://demo.adtags.mobi.s3-website-us-west-1.amazonaws.com/chrome-66-issue/index.html
If you load the page just by entering url and pressing enter (not using refresh), notice the console.log:
videojs.ima.js:1385 Ad error: AdError 400: There was an error playing the video ad. Caused by: AdError 1205: The browser prevented playback initiated without user interaction.
SdkImpl.onAdError @ videojs.ima.js:1385
video.js:498 VIDEOJS: adserror (Preroll)
video.js:21363 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

* First step

#### Expected Results

Player would give a catch() to the promise - or at least pause the video playback, so user knows that video is not going to play without interaction
<img width="1674" alt="screenshot 2018-06-01 14 45 22" src="https://user-images.githubusercontent.com/1171541/40868649-705497c2-65aa-11e8-8905-f74ddd91c01b.png">

#### Actual Results

Player is in play mode (see the pause button showing in the player).

### Versions

**videojs-contrib-ads version**: 6.3.0

**Video-js version**: 6.10.1

**Other plugins**: videojs-ima

### Platforms

**Browsers**: Chrome v66

**OS/Devices**: MacOS (and most likely Windows)

**Comment by mysuf** [comment]
Weird. It happens only on first load in tab. After soft/hard refresh it works everytime (windows + chrome 66)

**Comment by incompl** [comment]
You'll want to open an issue with videojs-ima. contrib-ads does not include autoplay handling.

**Comment by mysuf** [comment]
During testing, maybe I found bug in contrib-ads. Look at that flow:

VIDEOJS: ADS: Play middleware has been registered with videojs
VIDEOJS: ADS: Using playMiddleware to block content playback
VIDEOJS: ADS: Play call to Tech was terminated.
VIDEOJS: ADS: Received play event (BeforePreroll)
VIDEOJS: ADS: BeforePreroll -> Preroll
VIDEOJS: ADS: Received adsready event (Preroll)
VIDEOJS: ADS: Triggered readyforpreroll event (Preroll)
IMA ADS: called contentReadyForPreroll ->
IMA ADS: contentResumeRequested ->
IMA ADS: ads.isWatingForAdBreak() == true -> ads.skipLinearAdMode() 
VIDEOJS: ADS: skipLinearAdMode (Preroll)
DOMException(promise): play() failed because the user didn't interact with the document first
VIDEOJS: WARN: Unexpected startLinearAdMode invocation (Preroll)
IMA ADS: There was an error playing the video ad -> reseting
IMA ADS: checking if there contrib-ads is has some unfinished business ->
IMA ADS: ads.inAdBreak() == false -> 
IMA ADS: ads.isWatingForAdBreak() == true -> ads.skipLinearAdMode() 
VIDEOJS: WARN: Unexpected skipLinearAdMode invocation
VIDEOJS: ADS: adtimeout (Preroll)
DOMException(promise): play() failed because the user didn't interact with the document first

Note that I skip preroll and immediately call startLinearAdMode for midroll (which is bug on my side - it is actually one preroll ad). Anyway, then it refuses skipLinearAdMode and evaluates ads.isWatingForAdBreak() to true which leads to next Unexpected call of skipLinearAdMode invocation.

**Comment by incompl** [comment]
Ah yeah, that sounds like a bug. The latest version now logs out failed play events, so the logging output for this error may be clearer now. I was thinking yesterday this project may need handling for play rejection in some cases, and this sounds like it.

**Comment by bill5roses** [comment]
After logging this issue with videojs-ima, the recommendation is that this is either an issue with videojs-contrib-ads or videojs itself. @incompl, any chance we can be sure it is with videojs itself?
For reference see the issue over on videojs-ima: https://github.com/googleads/videojs-ima/issues/635

Thanks!

**Comment by incompl** [comment]
The latest version of contrib-ads logs out warnings [like this one](https://github.com/videojs/videojs-contrib-ads/blob/2ba443fce9036e1ba54448b187e7ad646ea1cd14/src/snapshot.js#L129) when a play is rejected. I think to investigate this issue we should see if one of those warnings is being hit, and then consider if recovery logic could be added in that spot.

**Comment by incompl** [comment]
We are going to release https://github.com/videojs/videojs-contrib-ads/pull/400 in the next contrib-ads release which I heard from that videojs-ima thread addresses the issue.

**Comment by incompl** [comment]
Released the above fix in 6.4.3, hopefully this addresses the issue for videojs-ima!
