### ISSUE TITLE
Mid-rolls need to be loaded from the beginning?

### ISSUE THREAD

**Issue by jpfranco** [videojs/videojs-contrib-ads#89]
Hey guys, so this seems somewhat apparent from the state diagram, but I wanted to confirm whether it is the case. 

So imagine that you want to use different ads on each scheduled mid-roll. One approach would be to load each ad (i.e. retrieve ad media source and metadata from the ad server) right before it is scheduled to play. This would distribute the loading time between each mid-roll instead of having a longer initialization time.

From what I've seen, this library doesn't currently allow you to trigger a "loading" state, similar to what happens right after ```contentupdate```, so if you wanted to play a mid-roll you would need to have all the relevant metadata loaded by that point and then you would call ```ads.startLinearAdMode()```. Is this correct? If so, is there a reason why ad loading is constrained to initialization time? Thanks

**Comment by dmlap** [comment]
You're right, there isn't a loading state for midrolls equivalent to the machinery for prerolls. This is mostly because a flash of content before prerolls is very obvious to viewers, and since many ad integrations built on top of contrib-ads load asynchronously, it's impossible for them to prevent playback before they've completed loading.

An advanced ad implementation could queue up midrolls ahead of the ad break, which would be pretty cool. Most implementations I've seen just put up a spinner and wait to start the midroll process until they've called startLinearAdMode(), though.

**Comment by jpfranco** [comment]
Thanks for the reply! We went the spinner route for now.
